"""create history

Revision ID: e27ddb889e8d
Revises: 
Create Date: 2025-02-28 02:31:46.986034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27ddb889e8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('pacient_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historys_doctor_id'), 'historys', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_historys_hospital_id'), 'historys', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_historys_pacient_id'), 'historys', ['pacient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historys_pacient_id'), table_name='historys')
    op.drop_index(op.f('ix_historys_hospital_id'), table_name='historys')
    op.drop_index(op.f('ix_historys_doctor_id'), table_name='historys')
    op.drop_table('historys')
    # ### end Alembic commands ###
