"""create timetable

Revision ID: 7b12139075ae
Revises: 
Create Date: 2025-02-06 01:22:06.476844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b12139075ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('from_column', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('to', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_doctor_id'), 'timetable', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_timetable_hospital_id'), 'timetable', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_hospital_id'), table_name='timetable')
    op.drop_index(op.f('ix_timetable_doctor_id'), table_name='timetable')
    op.drop_table('timetable')
    # ### end Alembic commands ###
